name: Build Android on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: production
