/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/ProductDetails`; params?: Router.UnknownInputParams; } | { pathname: `/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/QRScanner`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/Notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductList`; params?: Router.UnknownOutputParams; } | { pathname: `/QRScanner`; params?: Router.UnknownOutputParams; } | { pathname: `/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Login${`?${string}` | `#${string}` | ''}` | `/Notifications${`?${string}` | `#${string}` | ''}` | `/ProductDetails${`?${string}` | `#${string}` | ''}` | `/ProductList${`?${string}` | `#${string}` | ''}` | `/QRScanner${`?${string}` | `#${string}` | ''}` | `/Register${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/ProductDetails`; params?: Router.UnknownInputParams; } | { pathname: `/ProductList`; params?: Router.UnknownInputParams; } | { pathname: `/QRScanner`; params?: Router.UnknownInputParams; } | { pathname: `/Register`; params?: Router.UnknownInputParams; } | { pathname: `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
